Homework1 + Homework2
ok-technopolis-2021/Zhidkov_Denis pull request #3
Opened 2021-10-13 11:10 UTC by DenZhid

Жидков Денис, составлена корректная разметка и написан стиль для страницы

2021-10-20 23:20 UTC, aqus commented
Зря закрыли первый реквест, как раз так и нужно было делать: для одной ДЗ - 1 реквест

2021-10-20 23:47 UTC, aqus requested changes
- font-style - по умолчанию normal, не нужно его добавлять к каждому элементу с текстом
- не нужно ограничивать элементы по ширине и высоте, это можно создать проблемы, когда контента станет больше. ПРосто убрать и выровнять раскладкой, где поедет
- все, что связано со шрифтом наследуется из body, не нужно это многжество раз дублировать

2021-10-20 23:47 UTC, aqus commented on res/web-pages/main-page.html
> +            <section class="cv-profession">Web Developer</section>
- не хорошо использовать везде `section`
https://html.spec.whatwg.org/multipage/sections.html#the-section-element - тут документация

Небольшие выдержки:

> The section element represents a generic section of a document or application. A section, in this context, is a thematic grouping of content, typically with a heading.

то есть `section` используется для тематической группировки, и по-хорошему у каждой секции должен быть заголовок h1-h6

> The section element is not a generic container element. When an element is needed only for styling purposes or as a convenience for scripting, authors are encouraged to use the div element instead. A general rule is that the section element is appropriate only if the element's contents would be listed explicitly in the document's outline.

Если коротко, если хочется использовать блоки для стилизации - нужно использовать `div`, для группировки и для явного выделения контента - `section`

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    color: #FFFFFF;
уже есть в body

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    height: 44px;
не нужно ограничивать ширину и высоту, если заватра контента станет больше, все станет выглядеть некрасиво, так как текст будет наезжать на другие элементы

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    font-style: normal;
по умолчанию normal

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    color: #FFFFFF;
уже есть в body

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    height: 23px;
аналогично имени, не нужно ограничивать размеры, иначе при изменении размера контента он может наехать на соседние элементы

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    font-style: normal;
по умолчанию normal

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    font-weight: normal;
по умолчанию normal

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    font-size: 20px;
уже есть в body

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    width: 24px;
как-то они не совсем 24px
![image](https://user-images.githubusercontent.com/5273083/138186700-f56e682d-ef3f-4f74-85ce-f28c4d1bf927.png)

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    width: 24px;
так сучилось потому, что не очень корректно загружаются ресурсы и вот так распер alt текст, это тоже нужно учитывать

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    height: 20px;
снова, не нужно ограничивать размеры, если захотим туда написать что-то другое - нужно будет менять размеры, что не очень хорошо, нужно, чтобы размеры подстраивались под размер контента

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    color: #FFFFFF;
есть в body

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    font-weight: normal;
по умолчанию normal оба

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    height: 16px;
снова ограничение по размеру

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    font-weight: normal;
по умолчанию normal оба

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    color: #FFFFFF;
есть в body

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    padding: 244px 161px 247px 162px;
странный паддинг, можно без него

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    height: 104px;
снова ограничение размеров, сейчас контент больше, чем размер блока
![image](https://user-images.githubusercontent.com/5273083/138187140-d283bcfd-f9a9-41df-987a-70235a56c636.png)

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    margin: 0 0 0 0;
можно один 0

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    height: 71px;
не нужно фиксировать
вложенный элемент больше чем обертка

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    font-style: normal;
убрать

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    color: #FFFFFF;
есть в body

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    height: 25px;
убрать размеры

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    font-weight: normal;
убрать

2021-10-20 23:47 UTC, aqus commented on res/styles/main-style.css
> +    color: #FFFFFF;
есть в body

2021-10-23 11:34 UTC, DenZhid commented
Исправил все замечания кроме проблем с alt текстом и, возможно, контентом кнопки

2021-11-01 09:54 UTC, DenZhid commented
Всё исправлено

2021-11-09 21:25 UTC, aqus approved these changes
2 ДЗ - 7.5 баллов
Исправлены не все замечания, не соответствует макету
![image](https://user-images.githubusercontent.com/5273083/141006624-33c3a6c8-63af-481c-82df-f07694266502.png)

2021-11-09 21:25 UTC, aqus commented on res/styles/main-style.css
> +.github-img, .vk-img, .ok-img {
может тогда просто дать один абстрактный класс и не использовать 3 разных, потому что они делают одно и то же

2021-11-09 21:25 UTC, aqus commented on res/styles/main-style.css
> +    height: 180px;
если фото будет квадратным, то будет все хорошо, если использовать прямоугольное фото, то исказятся пропорции поэтому для таких случаев лучше фиксировать только одну сторону или класть фото в background в блок

2021-11-09 21:25 UTC, aqus commented on res/styles/main-style.css
> +    height: 509px;
не нужно ограничивать высоту, пусть ограничивается родителем и регулируется отступами
При добавлении контента получается вот так
![image](https://user-images.githubusercontent.com/5273083/141005986-2a4481a7-dd0b-48e2-88a0-d3229ee36422.png)

2021-11-09 21:25 UTC, aqus commented on res/styles/main-style.css
> +button {
лучше не использовать селектор по тегу

2021-11-09 21:25 UTC, aqus commented on res/styles/main-style.css
> +    height: 46px;
не нужно ограничивать кнопку по размеру, пусть регулируется внутренними отступами, иначе при добавлении контента он может не влезть
![image](https://user-images.githubusercontent.com/5273083/141007148-2fa5e249-d58e-4f5e-bebb-60697d19d86a.png)

2021-11-29 12:07 UTC, merged